Simplify lpc periph
3mdeb/verilog-lpc-module pull request #9
Opened 2023-02-08 18:12 UTC by krystian-hebel

2023-02-24 09:54 UTC, miczyg1 commented
Few things I noticed on the simulation before looking deeply into code:
![image](https://user-images.githubusercontent.com/30656491/221143969-f1f6ca2e-a263-421e-add4-bdb4d87bd2dd.png)
Above image shows correct write cycle, but the DATA phase is incorrectly decoded, the nibbles are swapped (wrong endianess). Possibly it is a wrong code in the test bench or the LPC peripheral source (will have to check it).

I am also wondering on the START latch moment. LPC spec says:
```
The peripheral must always use the last
START value when LFRAME# was active. For example, if LFRAME# is active for two
consecutive clocks, the peripheral should ignore the value during the first clock and only use the
second.
```

and 

```
After the final START value is driven, and when the host is ready to begin the cycle, the host
de-asserts LFRAME#. The peripheral must use the START value driven when LFRAME# is deasserted
```

And about START phase:

```
This field indicates the start or stop of a transaction. All state peripheral machines will go to a state
which monitors LAD[3:0] for this field when LFRAME# is asserted. The START field is valid on
the last clock that LFRAME# is asserted. While LFRAME# is asserted, this field may take on
many values, so peripherals should not make any assumptions on the validity of this field until
LFRAME# is de-asserted.
```

So START is being probed at rising edges currently, but the spec only mentions clocks (no edges whatsoever). According to spec START is latched as final value on LFRAME# de-assertion. In the test bench it looks like the START condition is latched on the last rising edge of the clock before LFRAME# de-assertion. And in this particular case:

![image](https://user-images.githubusercontent.com/30656491/221145717-803191c2-4018-4fca-84bd-b2c99c73b8e2.png)

The state machine is switching to `LPC_ST_START` (0x2) but the length of this state is incorrect. It should finish state 0x2 at the moment of LFRAME# deassertion, because it missed the `LPC_ST_CYCTYPE_RD` (0x3) state which should decode the LAD equal 0x2 for a write cycle. Thus I think something is wrong how LFRAME and START condition is interpreted.

Based on that I suggest a test bench extension so that LFRAME is low in more random moments, not exactly changing its state on clock edges but also in the middle of low or high level of clock. Also I would add test bench cases where LFRAME# signal is shorter than one clock cycle.

Also a side note for later: we will need SIRQ protocol implementation too. According to TCG spec: https://trustedcomputinggroup.org/wp-content/uploads/PC-Client-Specific-Platform-TPM-Profile-for-TPM-2p0-v1p05p_r14_pub.pdf

`The TPM SHALL support asserting any of the IRQ[0:15]. The TPM SHALL NOT assert PIRQ[A:D] in the SIRQ stream.`

Where `SHALL` is interpreted as follows according to RFC-2119:

`MUST -  This word, or the terms "REQUIRED" or "SHALL", mean that the definition is an absolute requirement of the specification.`

2023-02-24 10:10 UTC, miczyg1 commented on lpc_periph.v
> -    // Master Interface
@krystian-hebel I wish we could use separate PRs to fix indentations... Now the diff is unreadable...

2023-02-24 10:14 UTC, miczyg1 requested changes
I find it hard to continue review, because the diff is totally unreadable because of indentation changes. Please create a separate PR for indentation changes if possible.

2023-02-27 10:02 UTC, krystian-hebel commented on lpc_periph.v
> -    // Master Interface
I've created #10 and #11 and changed target of this PR.

2023-02-27 10:16 UTC, krystian-hebel commented
> Above image shows correct write cycle, but the DATA phase is incorrectly decoded, the nibbles are swapped (wrong endianess). Possibly it is a wrong code in the test bench or the LPC peripheral source (will have to check it).

Fixed in https://github.com/3mdeb/verilog-lpc-module/pull/9/commits/6d49abfa189fdcfdccf39f1dbcef85a0b7328df0, wrong code was both in TB as well as in implementation, hence TB didn't print any errors.

> I am also wondering on the START latch moment. LPC spec says: (...)
> So START is being probed at rising edges currently, but the spec only mentions clocks (no edges whatsoever). According to spec START is latched as final value on LFRAME# de-assertion. In the test bench, it looks like the START condition is latched on the last rising edge of the clock before LFRAME# de-assertion. But what if LFRAME# de-asserts or asserts on rising edge of clock?

Then you have a hazard that would behave differently on HW than in simulation, so a testbench wouldn't be able to catch it. Whether in simulation LFRAME# or clock transition happens first depends more so on the TB code than module implementation, so it wouldn't tell us anything useful.

> I suggest a test bench extension so that LFRAME# is low in more random moments, not exactly changing its state on clock edges but also in the middle of low or high level of clock. Also I would add test bench cases where LFRAME# signal is shorter than one clock cycle.

Do you still insist on it after my explanation above?

> Also a side note for later: we will need SIRQ protocol implementation too.

Should I open a new PR for it or can I add it here?

2023-02-28 10:12 UTC, miczyg1 commented
> > I suggest a test bench extension so that LFRAME# is low in more random moments, not exactly changing its state on clock edges but also in the middle of low or high level of clock. Also I would add test bench cases where LFRAME# signal is shorter than one clock cycle.
> 
> Do you still insist on it after my explanation above?

Not insisting, just suggesting.

> 
> > Also a side note for later: we will need SIRQ protocol implementation too.
> 
> Should I open a new PR for it or can I add it here?

I would appreciate new PR, what you already did https://github.com/3mdeb/verilog-lpc-module/pull/12

2023-02-28 10:16 UTC, miczyg1 commented
@krystian-hebel I have merged the two PRs that you extracted from this PR. Now I don't see `fix endianness of data for write cycles` commit on the main branch yet, so there are still some things unmerged in this PR. COuld you clean it up and rebase?

2023-02-28 10:38 UTC, krystian-hebel commented
Those 2 PRs you merged are supposed to be a base of this one, not to substitute it. Endianness is fixed in this PR, in last commit (https://github.com/3mdeb/verilog-lpc-module/pull/9/commits, on the very bottom of list).

2023-02-28 11:07 UTC, miczyg1 commented
> Those 2 PRs you merged are supposed to be a base of this one, not to substitute it. Endianness is fixed in this PR, in last commit (https://github.com/3mdeb/verilog-lpc-module/pull/9/commits, on the very bottom of list).

Okay thanks for explanation. I will look on the waves again to check if errors are really fixed

2023-03-01 14:53 UTC, miczyg1 commented
Issue with nibble endianess on write cycles fixed. Confirmed with the waveforms

2023-03-01 15:11 UTC, miczyg1 requested changes

2023-03-01 15:11 UTC, miczyg1 commented on lpc_periph.v
> +          // FIXME: testbench shows x's in LAD exactly at this point, maybe use Gray codes for FSM?
@krystian-hebel is this still valid? I can't find any point on the waveform that would indicate LAD having XXXX except the very beginning when all signals are initialized.

2023-03-01 15:15 UTC, krystian-hebel commented on lpc_periph.v
> +          // FIXME: testbench shows x's in LAD exactly at this point, maybe use Gray codes for FSM?
It didn't show on waveform even when it was detected by this code. It probably has to do with different assignment types used in different places.

2023-03-07 15:28 UTC, miczyg1 approved these changes

2023-03-07 15:28 UTC, merged